<?php

namespace ScalofrioBundle\Repository;

/**
 * CargoclienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoclienteRepository extends \Doctrine\ORM\EntityRepository
{
}
