<?php

namespace ScalofrioBundle\Repository;

/**
 * ComercialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComercialRepository extends \Doctrine\ORM\EntityRepository
{
}
