<?php

namespace ScalofrioBundle\Repository;

/**
 * EstablecimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstablecimientosRepository extends \Doctrine\ORM\EntityRepository
{
}
