<?php

namespace ScalofrioBundle\Repository;

/**
 * EstablecimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstablecimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
