<?php

namespace ScalofrioBundle\Repository;

/**
 * IncidenciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidenciasRepository extends \Doctrine\ORM\EntityRepository
{
}
