<?php

namespace ScalofrioBundle\Repository;

/**
 * Incidencias_repuestosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Incidencias_repuestosRepository extends \Doctrine\ORM\EntityRepository
{
}
