<?php

namespace ScalofrioBundle\Repository;

/**
 * MaquinasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaquinasRepository extends \Doctrine\ORM\EntityRepository
{
}
