<?php

namespace ScalofrioBundle\Repository;

/**
 * MaquinasClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaquinasClienteRepository extends \Doctrine\ORM\EntityRepository
{
}
