<?php

namespace ScalofrioBundle\Repository;

/**
 * RepuestosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepuestosRepository extends \Doctrine\ORM\EntityRepository
{
}
