<?php

namespace ScalofrioBundle\Repository;

/**
 * ResultadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadosRepository extends \Doctrine\ORM\EntityRepository
{
}
