<?php

namespace ScalofrioBundle\Repository;

/**
 * RutasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RutasRepository extends \Doctrine\ORM\EntityRepository
{
}
