<?php

namespace ScalofrioBundle\Repository;

/**
 * SubestablecimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubestablecimientosRepository extends \Doctrine\ORM\EntityRepository
{
}
