<?php

namespace ScalofrioBundle\Repository;

/**
 * TextoCorreoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextoCorreoRepository extends \Doctrine\ORM\EntityRepository
{
}
