scalofrio_index:
    path:     /index
    defaults: { _controller: ScalofrioBundle:User:index }

scalofrio_homepage:
    path: /
    defaults: {_controller: ScalofrioBundle:User:home}

############# APARTADO DE INCIDENCIAS ################

scalofrio_incidencia_add:
    path:     /incidencia/add
    defaults: { _controller: ScalofrioBundle:User:incidenciaAdd }

scalofrio_incidencia_create:
    path: /incidencia/create
    defaults: {_controller: ScalofrioBundle:User:createIncidencia }
    methods: POST

scalofrio_incidencia_redirect_add:
    path: /incidencia/create
    defaults:
        _controller: ScalofrioBundle:User:incidenciaAdd
        path: /incidencia/add
        permanent: true

scalofrio_incidencia_edit:
    path:     /incidencia/edit/{id}
    defaults: { _controller: ScalofrioBundle:User:IncidenciaEdit }

scalofrio_incidencia_update:
    path:     /incidencia/update/{id}
    defaults: { _controller: ScalofrioBundle:User:incidenciaUpdate }
    methods: [POST, PUT]

scalofrio_incidencia_redirect_edit:
    path: /incidencia/update{id}
    defaults:
        _controller: ScalofrioBundle:User:incidenciaEdit
        path: /incidencia/edit/{id}
        permanent: true

scalofrio_incidencia_view:
    path:     /incidencia/view/{id}
    defaults: { _controller: ScalofrioBundle:User:incidenciaView }

scalofrio_incidencia_delete:
    path:     /incidencia/delete/{id}
    defaults: { _controller: ScalofrioBundle:User:incidenciaDelete }
    methods: [POST, DELETE]



############# EXPORTAR A CSV ################

scalofrio_export:
    path: /index/export
    defaults: { _controller: ScalofrioBundle:User:generateCsv }

scalofrio_usuarios_export:
    path: /user/export
    defaults: { _controller: ScalofrioBundle:User:generateUserCsv }

scalofrio_avisos_export:
    path: /avisos/export
    defaults: { _controller: ScalofrioBundle:IncidenciasClientes:generateAvisoCsv }



############# APARTADO DE USUARIOS ################

scalofrio_user_add:
    path:     /user/add
    defaults: { _controller: ScalofrioBundle:User:UserAdd }

scalofrio_user_create:
    path: /user/create
    defaults: {_controller: ScalofrioBundle:User:createUser }
    methods: POST

scalofrio_user_redirect_add:
    path: /user/create
    defaults:
        _controller: ScalofrioBundle:User:UserAdd
        path: /user/add
        permanent: true

scalofrio_user_edit:
    path:   /user/edit{id}
    defaults: { _controller: ScalofrioBundle:User:userEdit }

scalofrio_user_update:
    path:     /user/update/{id}
    defaults: { _controller: ScalofrioBundle:User:userUpdate }
    methods: [POST, PUT]

scalofrio_user_redirect_edit:
    path: /user/update{id}
    defaults:
        _controller: ScalofrioBundle:User:userEdit
        path: /user/edit/{id}
        permanent: true

scalofrio_user_list:
    path:   /user/list
    defaults: { _controller: ScalofrioBundle:User:userList }


############# APARTADO DE COMERCIALES ################

scalofrio_comercial_add:
    path:     /comercial/add
    defaults: { _controller: ScalofrioBundle:User:ComercialAdd }

scalofrio_comercial_create:
    path: /comercial/create
    defaults: {_controller: ScalofrioBundle:User:createComercial }
    methods: POST

scalofrio_comercial_redirect_add:
    path: /user/comercial
    defaults:
        _controller: ScalofrioBundle:User:ComercialAdd
        path: /comercial/add
        permanent: true



############# APARTADO DE CLIENTES ################
scalofrio_cliente_list:
    path:   /cliente/list
    defaults: { _controller: ScalofrioBundle:User:clienteList }

scalofrio_cliente_view:
    path:   /cliente/view{id}
    defaults: { _controller: ScalofrioBundle:User:clienteView }

scalofrio_establecimientos_create:
    path: /establecimiento/create
    defaults: {_controller: ScalofrioBundle:User:createEstablecimientos }
    methods: POST

scalofrio_subestablecimientos_create:
    path: /subestablecimiento/create
    defaults: {_controller: ScalofrioBundle:User:createSubestablecimientos }
    methods: POST

scalofrio_cliente_edit:
    path:   /cliente/edit{id}
    defaults: { _controller: ScalofrioBundle:User:clienteEdit }

scalofrio_cliente_update:
     path:     /cliente/update/{id}
     defaults: { _controller: ScalofrioBundle:User:clienteUpdate }
     methods: [POST, PUT]

scalofrio_cliente_redirect_edit:
    path: /cliente/update{id}
    defaults:
         _controller: ScalofrioBundle:User:clienteEdit
         path: /cliente/edit/{id}
         permanent: true

scalofrio_cliente_add:
    path:     /cliente/add
    defaults: { _controller: ScalofrioBundle:User:ClienteAdd }

scalofrio_cliente_create:
    path: /cliente/create
    defaults: {_controller: ScalofrioBundle:User:createCliente }
    methods: POST

scalofrio_cliente_redirect_add:
    path: /cliente/create
    defaults:
        _controller: ScalofrioBundle:User:ClienteAdd
        path: /cliente/add
        permanent: true




############# APARTADO DE GESTIONES ################

scalofrio_gestion_add:
    path:     /gestion/add
    defaults: { _controller: ScalofrioBundle:User:GestionAdd }

scalofrio_gestion_create:
    path: /gestion/create
    defaults: {_controller: ScalofrioBundle:User:createGestion }
    methods: POST

scalofrio_gestion_redirect_add:
    path: /gestion/create
    defaults:
        _controller: ScalofrioBundle:User:GestionAdd
        path: /gestion/add
        permanent: true


############# APARTADO DE MAQUINAS ################
scalofrio_maquinas_list:
    path:   /maquinas/list
    defaults: { _controller: ScalofrioBundle:User:maquinasList }

scalofrio_maquinas_view:
    path:   /maquinas/view{id}
    defaults: { _controller: ScalofrioBundle:User:maquinasView }

scalofrio_repuestos_create:
    path: /repuestos/create
    defaults: {_controller: ScalofrioBundle:User:createRepuestos }
    methods: POST

scalofrio_maquinas_edit:
    path:   /maquinas/edit{id}
    defaults: { _controller: ScalofrioBundle:User:maquinasEdit }

scalofrio_maquinas_update:
    path:     /maquinas/update/{id}
    defaults: { _controller: ScalofrioBundle:User:maquinasUpdate }
    methods: [POST, PUT]

scalofrio_maquinas_redirect_edit:
    path: /maquinas/update{id}
    defaults:
        _controller: ScalofrioBundle:User:maquinasEdit
        path: /maquinas/edit/{id}
        permanent: true

scalofrio_maquinas_add:
    path:     /maquinas/add
    defaults: { _controller: ScalofrioBundle:User:maquinasAdd }

scalofrio_maquinas_create:
    path: /maquinas/create
    defaults: {_controller: ScalofrioBundle:User:createMaquinas }
    methods: POST

scalofrio_maquinas_redirect_add:
    path: /maquinas/create
    defaults:
        _controller: ScalofrioBundle:User:maquinasAdd
        path: /maquinas/add
        permanent: true




############# AUTENTIFICACIÓN ################

scalofrio_login:
    path: /login
    defaults: {_controller: ScalofrioBundle:Security:login}

scalofrio_login_check:
    path: /login_check
    defaults: {_controller: ScalofrioBundle:Security:loginCheck}

scalofrio_logout:
    path: /logout



############# BUSCADOR ################

scalofrio_busqueda:
    path: /busqueda
    defaults: {_controller: ScalofrioBundle:User:busqueda }

scalofrio_busqueda_cliente:
    path: /busquedaCliente
    defaults: {_controller: ScalofrioBundle:User:busquedaCliente }

scalofrio_busqueda_user:
    path: /busquedaUsuario
    defaults: {_controller: ScalofrioBundle:User:busquedaUser }


############# INCIDENCIAS CLIENTES ################

scalofrio_incidenciaCliente_add:
  path: /incidenciaCliente/nueva
  defaults:
    { _controller: ScalofrioBundle:IncidenciasClientes:incidenciaClienteNew }

scalofrio_incidenciaCliente_create:
  path: /incidenciaCliente/create
  defaults:
    { _controller: ScalofrioBundle:IncidenciasClientes:incidenciaClienteCreate }
  methods: POST

scalofrio_incidenciaCliente_show:
  path: /incidenciaCliente/mostrar/{id}
  defaults:
    { _controller: ScalofrioBundle:IncidenciasClientes:incidenciaClienteShow }

scalofrio_incidenciaActualizarEstado:
  path: /incidenciaCliente/actualizarEstado/{id}
  defaults:
    { _controller: ScalofrioBundle:IncidenciasClientes:actualizarEstado }

scalofrio_listarIncidencias:
  path: /incidenciaCliente/historial
  defaults:
    { _controller: ScalofrioBundle:IncidenciasClientes:listar }


############ OBTENCIÓN DE ELEMENTOS EN LOS SELECTS ###########

obtener_establecimiento:
    pattern: /obtenerEstablecimientos/{idcliente}
    defaults: { _controller: ScalofrioBundle:User:obtenerEstablecimientos }

obtener_subestablecimiento:
    pattern: /obtenerSubestablecimientos/{idestablecimiento}
    defaults: { _controller: ScalofrioBundle:User:obtenerSubestablecimientos }

obtener_establecimiento_cliente:
    pattern: /obtenerEstablecimientosCliente/{idcliente}
    defaults: { _controller: ScalofrioBundle:IncidenciasClientes:obtenerEstablecimiento }

obtener_subestablecimiento_cliente:
    pattern: /obtenerSubestablecimientosCliente/{idcliente}
    defaults: { _controller: ScalofrioBundle:IncidenciasClientes:obtenerSubestablecimientosCliente }

obtener_cliente:
    pattern: /obtenerCliente/
    defaults: { _controller: ScalofrioBundle:IncidenciasClientes:obtenerCliente }

obtener_repuestos:
    pattern: /obtenerRepuestos/{idmaquina}
    defaults: { _controller: ScalofrioBundle:User:obtenerRepuestos }

obtener_incidencias_clientes:
    pattern: /obtenerIncidenciasClientes/
    defaults: { _controller: ScalofrioBundle:User:obtenerIncidenciasClientes }

seleccion_incidencia:
    pattern: /seleccionIncidencia/{idincidencia}
    defaults: { _controller: ScalofrioBundle:User:seleccionIncidencia }


####### APARTADO DE RESULTADOS ########
scalofrio_resultados_add:
    path:     /resultados/add
    defaults: { _controller: ScalofrioBundle:User:resultadosAdd }

scalofrio_resultados_create:
    path: /resultados/create
    defaults: {_controller: ScalofrioBundle:User:createResultados }
    methods: POST

scalofrio_resultados_redirect_add:
    path: /resultados/create
    defaults:
        _controller: ScalofrioBundle:User:resultadosAdd
        path: /resultados/add
        permanent: true


####### APARTADO DE RUTAS ########
scalofrio_rutas_add:
    path:     /rutas/add
    defaults: { _controller: ScalofrioBundle:User:rutasAdd }

scalofrio_rutas_create:
    path: /rutas/create
    defaults: {_controller: ScalofrioBundle:User:createRutas }
    methods: POST

scalofrio_rutas_redirect_add:
    path: /rutas/create
    defaults:
        _controller: ScalofrioBundle:User:rutasAdd
        path: /rutas/add
        permanent: true


####### APARTADO DE CARGOS DEL CLIENTE ########
scalofrio_cargos_add:
  path:     /cargos/add
  defaults: { _controller: ScalofrioBundle:User:cargosAdd }

scalofrio_cargos_create:
  path: /cargos/create
  defaults: {_controller: ScalofrioBundle:User:createCargos }
  methods: POST

scalofrio_cargos_redirect_add:
  path: /cargos/create
  defaults:
    _controller: ScalofrioBundle:User:cargosAdd
    path: /cargos/add


####### APARTADO DE MÁQUINAS DEL CLIENTE ########
scalofrio_maquinasCliente_add:
  path:     /maquinasCliente/add
  defaults: { _controller: ScalofrioBundle:User:maquinasClienteAdd }

scalofrio_maquinasCliente_create:
  path: /maquinasCliente/create
  defaults: {_controller: ScalofrioBundle:User:createMaquinasCliente }
  methods: POST

scalofrio_maquinasCliente_redirect_add:
  path: /maquinasCliente/create
  defaults:
    _controller: ScalofrioBundle:User:maquinasClienteAdd
    path: /maquinasCliente/add

    ####### APARTADO DE TEXTO EN LOS CORREOS ########
scalofrio_correo:
  path:   /user/correo/edit
  defaults: { _controller: ScalofrioBundle:User:textoCorreo }

scalofrio_correo_update:
  path:     /user/correo/update
  defaults: { _controller: ScalofrioBundle:User:textoCorreoUpdate }
  methods: [POST, PUT]